select
HD_TICKET.ID AS TICKET_ID,
HD_TICKET.SUMMARY AS SUMMARY,
HD_TICKET.CREATED AS DATE_CREATED,
HD_TICKET.TIME_CLOSED AS DATE_CLOSED,
HD_TICKET_CHANGE.TIMESTAMP AS DATE_CHANGE_OCCURRED,
HD_TICKET_CHANGE.COMMENT AS CHANGE_COMMENT,
HD_STATUS.NAME AS TICKET_STATUS,
HD_TICKET_CHANGE.DESCRIPTION AS CHANGE_DESCRIPTION,
case
	when HD_TICKET.HD_PRIORITY_ID = 0 then 'Emergency'
    when HD_TICKET.HD_PRIORITY_ID = 1 then 'High'
    when HD_TICKET.HD_PRIORITY_ID = 2 then 'Medium'
    when HD_TICKET.HD_PRIORITY_ID = 3 then 'Low'
end as "PRIORITY",
U1.USER_NAME AS TICKET_OWNER,
USER.USER_NAME AS TICKET_CREATOR,
HD_TICKET.RESOLUTION AS RESOLUTION,
case
	when HD_TICKET.SLA_NOTIFIED = '0000-00-00 00:00:00' then 'N/A'
end as "SLA_VIOLATED"
from
HD_TICKET
join HD_TICKET_CHANGE on HD_TICKET_CHANGE.HD_TICKET_ID = HD_TICKET.ID
join USER U1 on U1.ID = HD_TICKET.OWNER_ID
join USER on USER.ID = HD_TICKET.SUBMITTER_ID
join HD_STATUS on HD_STATUS.ID = HD_TICKET.HD_STATUS_ID
where
HD_TICKET.CREATED >= '2020-01-01 00:00:00' and HD_TICKET.CREATED <= '2020-12-31 23:59:59'
order by
HD_TICKET.ID asc