SELECT DISTINCT
  MACHINE.NAME AS COMPUTER_NAME,
  BIOS_SERIAL_NUMBER AS SERIAL_NUMBER,
  OS_NAME AS OPERATING_SYSTEM,
  CS_MODEL AS COMPUTER_MODEL,
  ASSET_DATA_5.FIELD_34 AS REPLACEMENT_DATE,
  ASSET_DATA_5.FIELD_30 AS CLASSIFICATION,
  ASSET_DATA_5.FIELD_41 AS COMPUTER_STATUS,
  ASSET_DATA_5.FIELD_42 AS STOCK_TYPE,
  CASE
    WHEN ASSET.ASSET_STATUS_ID = 0 THEN "N/A"
    WHEN ASSET.ASSET_STATUS_ID = 492 THEN "EXPIRED"
    WHEN ASSET.ASSET_STATUS_ID = 493 THEN "ACTIVE"
    WHEN ASSET.ASSET_STATUS_ID = 494 THEN "DISPOSED"
    WHEN ASSET.ASSET_STATUS_ID = 495 THEN "IN STOCK"
    WHEN ASSET.ASSET_STATUS_ID = 496 THEN "MISSING"
    WHEN ASSET.ASSET_STATUS_ID = 497 THEN "RESERVED"
    WHEN ASSET.ASSET_STATUS_ID = 498 THEN "REPAIRED"
    WHEN ASSET.ASSET_STATUS_ID = 499 THEN "STOLEN"
    WHEN ASSET.ASSET_STATUS_ID = 500 THEN "RETIRED"
  END AS "ASSET_STATUS"
FROM
  MACHINE
  JOIN ASSET ON ASSET.MAPPED_ID = MACHINE.ID
  JOIN ASSET_DATA_5 on ASSET_DATA_5.FIELD_19 = MACHINE.BIOS_SERIAL_NUMBER
WHERE
  (((ASSET.ASSET_STATUS_ID = 0 OR ASSET.ASSET_STATUS_ID = 495 OR ASSET.ASSET_STATUS_ID = 493)
  AND
 (ASSET_DATA_5.FIELD_41 LIKE '%Use%' OR ASSET_DATA_5.FIELD_41 LIKE '%Stock%'))
 AND
 (ASSET_DATA_5.FIELD_41 NOT LIKE '%Use%' AND ASSET.ASSET_STATUS_ID != 493))
ORDER BY
  COMPUTER_NAME ASC;
