SELECT DISTINCT
  FIELD_41 AS ASSET_STATUS,
  USER.USER_NAME AS ASSIGNED_TO,
  ASSET_DATA_VIEW_Location.NAME AS LOCATION,
  FIELD_19 AS NAME,
  ASSET_DATA_VIEW_Department.NAME AS DEPT,
  FIELD_39 AS ROOM_NUMBER,
  FIELD_22 AS ASSIGNMENT_TYPE,
  FIELD_31 AS FUNDS_USED,
  FIELD_27 AS DATE_PURCHASED,
  FIELD_34 AS REPLACEMENT_DATE,
  FIELD_26 AS DATE_ASSIGNED,
  FIELD_30 AS CLASSIFICATION,
  FIELD_42 AS STOCK_TYPE,
  FIELD_33 AS PO_NUMBER,
  CASE
    WHEN ASSET.ASSET_STATUS_ID = 0 THEN "N/A"
    WHEN ASSET.ASSET_STATUS_ID = 492 THEN "EXPIRED"
    WHEN ASSET.ASSET_STATUS_ID = 493 THEN "ACTIVE"
    WHEN ASSET.ASSET_STATUS_ID = 494 THEN "DISPOSED"
    WHEN ASSET.ASSET_STATUS_ID = 495 THEN "IN STOCK"
    WHEN ASSET.ASSET_STATUS_ID = 496 THEN "MISSING"
    WHEN ASSET.ASSET_STATUS_ID = 497 THEN "RESERVED"
    WHEN ASSET.ASSET_STATUS_ID = 498 THEN "REPAIRED"
    WHEN ASSET.ASSET_STATUS_ID = 499 THEN "STOLEN"
    WHEN ASSET.ASSET_STATUS_ID = 500 THEN "RETIRED"
  END AS "ASSET_STATUS"
FROM
  ASSET_DATA_5
  JOIN ASSET ON ASSET.NAME = FIELD_19
  JOIN USER ON USER.ID = ASSET.OWNER_ID
  JOIN ASSET_DATA_VIEW_Location ON ASSET_DATA_VIEW_Location.ASSET_ID = ASSET.LOCATION_ID
  JOIN ASSET_ASSOCIATION_VIEW ON ASSET_ASSOCIATION_VIEW.ASSET_ID = ASSET.ID
  JOIN ASSET_DATA_VIEW_Department ON ASSET_DATA_VIEW_Department.ASSET_ID = ASSET_ASSOCIATION_VIEW.ASSOCIATED_ASSET_ID
  WHERE
  FIELD_41 != 'Sold'
  AND
  FIELD_41 != 'Disposed'
  AND
  FIELD_41 != 'Stolen'
  AND
  FIELD_41 != 'Marked for Disposal'
  AND
  FIELD_41 != 'Marked for Return'
  AND
  ASSET.ASSET_STATUS_ID != 494
  AND
  (((FIELD_26 != '0000-00-00') AND (FIELD_27 != '0000-00-00')) AND (FIELD_34 != '0000-00-00'))
  AND 
  FIELD_19 NOT LIKE 'VM%'
  AND
  FIELD_34 > '2018-01-01';