select
HD_TICKET.ID AS 'Ticket #',
HD_TICKET.SUMMARY AS 'Summary',
HD_TICKET.HD_PRIORITY_ID as 'Priority',
HD_TICKET.CREATED as 'Date Created',
HD_TICKET.TIME_CLOSED as 'Date closed',
HD_TICKET_CHANGE.DESCRIPTION as 'Change Description',
HD_TICKET_CHANGE.TIMESTAMP as 'Time Change Occurred'
from
HD_TICKET
join HD_TICKET_CHANGE on HD_TICKET.ID = HD_TICKET_CHANGE.HD_TICKET_ID
where
(HD_TICKET_CHANGE.DESCRIPTION LIKE '%Changed ticket Owner from%'
AND HD_TICKET_CHANGE.DESCRIPTION NOT LIKE '%Changed ticket Owner from "Unassigned" to%')
AND HD_TICKET.CREATED >= '2020-01-01 00:00:00' and HD_TICKET.CREATED <= '2020-12-31 23:59:59'
