SELECT 
ASSET.ID AS PRIMARY_KEY,
ASSET.NAME AS SERIAL_NUMBER,
ASSET.ASSET_DATA_ID AS ASSET_DATA_5_ID,
ASSET.LOCATION_ID AS LOCATION_ID,
ASSET.MAPPED_ID AS MACHINE_MAPPED_ID,
ALOC.NAME AS LOCATION,
A.NAME AS DEPARTMENT,
FIELD_10007 AS REPLACEMENT_DATE_QUARTER,
FIELD_10008 AS PURCHASE_DATE_QUARTER,
FIELD_10010 AS NOTES,
FIELD_10011 AS ASSIGNMENT_TYPE,
FIELD_10012 AS FUNDING_TYPE,
FIELD_10031 AS PURCHASE_DATE,
FIELD_10030 AS YEAR_ASSIGNED,
FIELD_10032 AS REPLACEMENT_YEAR,
FIELD_10033 AS PO_NUMBER,
FIELD_10036 AS ROOM_NUMBER
FROM
ASSET_DATA_5
JOIN ASSET ON ASSET.ASSET_DATA_ID = ASSET_DATA_5.ID
JOIN ASSET_ASSOCIATION AA ON AA.ASSET_ID = ASSET.ID AND AA.ASSET_FIELD_ID=10034
JOIN ASSET A ON A.ID = AA.ASSOCIATED_ASSET_ID
JOIN ASSET ALOC ON ALOC.ID = ASSET.LOCATION_ID
ORDER BY ASSET.ID ASC;