select 
HD_TICKET_CHANGE.HD_TICKET_ID as 'TickNum',
HD_TICKET.TIME_CLOSED,
HD_TICKET_CHANGE.TIMESTAMP as 'Time of change',
OWNER.USER_NAME as 'Ticket Owner',
SUBMITTER.USER_NAME as 'Submitted By',
USER.USER_NAME as 'Changed By',
HD_TICKET_CHANGE.DESCRIPTION,
HD_TICKET_CHANGE.COMMENT
from
HD_TICKET_CHANGE
join USER on USER.ID = HD_TICKET_CHANGE.USER_ID
join HD_TICKET on HD_TICKET.ID = HD_TICKET_CHANGE.HD_TICKET_ID
join USER OWNER on OWNER.ID = HD_TICKET.OWNER_ID
join USER SUBMITTER on SUBMITTER.ID = HD_TICKET.SUBMITTER_ID
join HD_STATUS on HD_STATUS.ID = HD_TICKET.HD_STATUS_ID
where 
((((HD_TICKET_CHANGE.DESCRIPTION like '%Team%') or (HD_TICKET_CHANGE.DESCRIPTION like '%Infrastructure%') or (HD_TICKET_CHANGE.DESCRIPTION like '%Enterprise%') or (HD_TICKET_CHANGE.DESCRIPTION like '%Client%'))))
and
HD_TICKET_CHANGE.DESCRIPTION not like '%Closed%'
and
HD_TICKET.TIME_CLOSED < HD_TICKET_CHANGE.TIMESTAMP
and
HD_STATUS.STATE like 'Closed'
order by
HD_TICKET_CHANGE.HD_TICKET_ID asc