select 
HD_TICKET.ID as 'Ticket Number',
HD_TICKET.TITLE as 'Ticket Title',
HD_CATEGORY.NAME as 'Category',
HD_PRIORITY.NAME as 'Priority',
HD_STATUS.NAME as 'Ticket State',
OWNER.FULL_NAME as 'Ticket Owner',
HD_TICKET.TIME_OPENED as 'Time Created',
HD_TICKET.TIME_CLOSED as 'Time Closed',
HD_TICKET.SLA_NOTIFIED as 'SLA Violated',
SUBMITTER.FULL_NAME as 'Ticket Submitter'
from HD_TICKET
join USER OWNER on OWNER.ID = HD_TICKET.OWNER_ID
join USER SUBMITTER on SUBMITTER.ID = HD_TICKET.SUBMITTER_ID
join HD_CATEGORY on HD_CATEGORY.ID = HD_TICKET.HD_CATEGORY_ID
join HD_PRIORITY on HD_PRIORITY.ID = HD_TICKET.HD_PRIORITY_ID
join HD_STATUS on HD_STATUS.ID = HD_TICKET.HD_STATUS_ID
join USER MANAGER on MANAGER.ID = OWNER.MANAGER_ID
where
HD_TICKET.TIME_CLOSED > (NOW() - INTERVAL 7 DAY)
#and
#HD_STATUS.NAME != 'Closed'
and 
((MANAGER.ID = 6406) or (MANAGER.ID = 16))
and 
HD_TICKET.SLA_NOTIFIED not like '0000-00-00 00:00:00'